/**:
  ros__parameters:
    host_ip: 127.0.0.1
    sensor_ip: 127.0.0.1
    data_port: 7502
    imu_port: 7503
    packet_mtu_size: 16640
    launch_hw: true
    setup_sensor: true
    frame_id: ouster
    diag_span: 1000
    scan_phase: 0.0
    min_range: 0.3
    max_range: 200.0
    sensor_model: OS1-128
    return_mode: SingleStrongest
    columns_per_frame: 1024
    calibration_file: ""
